#ifndef H_FUNCTIONS
#define H_FUNCTIONS




#include <sys/time.h> /* struct timeval. */

#include "rpc_services.h" /* This one is auto-generated by rpcgen. */




int my_gettimeofday(struct timeval * tv);
int my_add3(int a, int b, int c, int * result);

int sm_next(void);
int sm_prev(void);
int sm_set_label(const char * label, int idx);
int sm_get_current_label(char * label_arr);
int sm_get_all_info(sm_all_info_t * info);




#endif /* #ifndef H_FUNCTIONS */

