/*
  repacky - my toy RPC code
  Copyright (C) 2024 Kamil Ignacak

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; either version 2
  of the License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/




#define _POSIX_C_SOURCE 200809L




#include <ctype.h>
#include <errno.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "rpc_services.h" /* This one is auto-generated by rpcgen. */

#include "rpc.h"




CLIENT * g_client;




int client_lib_rpc_init(const char * rpc_server)
{
	g_client = clnt_create(rpc_server, MY_RPC_SERVER, MY_RPC_FUNCTIONS, "tcp");
	if (g_client == NULL) {
		clnt_pcreateerror(rpc_server);
		return -1;
	}

	return 0;
}




int client_lib_rpc_deinit(void)
{
	clnt_destroy(g_client);
	return 0;
}


