/*
  repacky - my toy RPC code
  Copyright (C) 2024 Kamil Ignacak

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; either version 2
  of the License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/




/*
  Implementation of service that is served over RPC: "gettimeofday"
  functionality.
*/




#define _POSIX_C_SOURCE 200112L /* strerror_r() */




#include <rpc/rpc.h>


#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <sys/time.h>

#include "rpc_services.h" /* This file is generated by rpcgen. */




bool_t fn_gettimeofday_1_svc(my_timeval_t * out, __attribute__((unused)) struct svc_req * req)
{
	struct timeval now = { 0 };
	out->rv = gettimeofday(&now, NULL);
	if (0 == out->rv) {
		out->tv_sec = now.tv_sec;
		out->tv_usec = now.tv_usec;
		fprintf(stdout, "[II] RPC server: current time = %u.%u\n", out->tv_sec, out->tv_usec);
	} else {
		char buf[32] = { 0 };
		strerror_r(errno, buf, sizeof (buf));
		fprintf(stderr, "[EE] RPC server: can't get current time: %s\n", buf);
	}
	return TRUE;
}

