/*
  repacky - my toy RPC code
  Copyright (C) 2024 Kamil Ignacak

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; either version 2
  of the License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/




#include <rpc/rpc.h>

#include <stdio.h>
#include <string.h>

#include "rpc_services.h" /* This file is generated by rpcgen. */




char g_test_data[TEST_THREADS_COUNT][TEST_DATA_SIZE];




bool_t fn_transport_test_set_1_svc(char * data_ptr, int idx, __attribute((unused)) int * unused, __attribute((unused)) struct svc_req * req)
{
	memcpy(g_test_data[idx], data_ptr, TEST_DATA_SIZE);

	return TRUE;
}




bool_t fn_transport_test_get_1_svc(int idx, char * data_arr, __attribute((unused)) struct svc_req * req)
{
	memcpy(data_arr, g_test_data[idx], TEST_DATA_SIZE);

	return TRUE;
}

